name: mickey
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.17
  - pip=23.2.1
  - pip:
    - einops==0.6.1
    - lazy-loader==0.3
    - lightning-utilities==0.9.0
    - matplotlib==3.7.2
    - numpy==1.24.4
    - omegaconf==2.3.0
    - open3d==0.17.0
    - opencv-python==4.8.0.74
    - protobuf==4.23.4
    - pytorch-lightning==2.0.6
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.1
    - timm==0.6.7
    - torch==2.0.1
    - torchmetrics==1.0.2
    - torchvision==0.15.2
    - tqdm==4.65.1
    - transforms3d==0.4.1
    - xformers==0.0.20
    - yacs==0.1.8
    - albumentations>=1.4.0
    - boto3>=1.26.16
    - braceexpand>=0.1.7
    - diffusers==0.20.0
    - ftfy==6.1.0
    - huggingface_hub>=0.20.0
    - opencv_python_headless>=4.6.0.66
    - pandas>=1.5.2   
    - Pillow>=9.3.0
    - PyYAML>=6.0
    - regex>=2022.10.31
    - Requests>=2.31.0
    - scikit_learn>=1.1.3
    - setuptools>=61.0
    - tokenizers>=0.15.2
    - datasets>=0.17
    - wandb>=0.13.5
    - webdataset>=0.2.86
